version: '3'

services:
  web:
    build: .
    command: honcho start
    environment:
      - DJANGO_SETTINGS_MODULE=seriesly.settings
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "127.0.0.1:5023:5000"
    volumes:
      - ./db.sqlite3:/code/db.sqlite3
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: "redis:alpine"
