# Generated by Django 2.0 on 2018-01-27 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("series", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="show",
            name="country",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="show",
            name="network",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="show",
            name="timezone",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
