# Generated by Django 3.2.6 on 2021-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20180127_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
